Repository aws/aws-sam-cli-app-templates, pull requests merged in 2022-12, with the labels that each got.

#323 fix: non-custom GH action for `manifest.json`
  .github/workflows/manifest-backward-compability-check.yml
Labels: pr/internal

#317 Update Go compiler version for the go1.x Docker Image template
  go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/Dockerfile
Labels: pr/external, maintainer/need-followup, area/docker, area/build

#322 Add template for using Go with Docker on the provided.al2 images
  manifest-v2.json
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/README.md
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/__init__.py
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/cookiecutter.json
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/requirements-dev.txt
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/tests/__init__.py
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/tests/test_bake_project.py
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/README.md
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/Dockerfile
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/go.mod
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/go.sum
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/main.go
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/main_test.go
  provided.al2/go/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/template.yaml
  tests/integration/build_invoke/test_build_invoke_go1_x.py
Labels: pr/external, stage/needs-triage

#319 update module dependencies for go templates
  go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/go.mod
  go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/hello-world/go.sum
  go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/hello-world/go.mod
  go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/hello-world/go.sum
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockBuyer/go.mod
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockBuyer/go.sum
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockChecker/go.mod
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockChecker/go.sum
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockSeller/go.mod
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockSeller/go.sum
  provided.al2/go/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/hello-world/go.mod
  provided.al2/go/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/hello-world/go.sum
  provided.al2/go/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockBuyer/go.mod
  provided.al2/go/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockBuyer/go.sum
  provided.al2/go/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockChecker/go.mod
  provided.al2/go/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockChecker/go.sum
  provided.al2/go/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockSeller/go.mod
  provided.al2/go/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockSeller/go.sum
Labels: pr/external, stage/needs-triage

#320 Remove rd.xml from native aot and use TrimMode partial
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/rd.xml
Labels: pr/external, maintainer/need-response, stage/needs-triage
