Repository aws/aws-sam-cli-app-templates, pull requests merged in 2022-11, with the labels that each got.

#286 Fix issue #285 - Changes to Lambda Powertools for TypeScript template
  nodejs14.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
Labels: pr/external

#288 Issue 287: Nodejs16.x support for "Hello World Example TypeScript w/ Lambda Powertools"
  manifest-v2.json
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/.gitignore
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/README.md
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/cookiecutter.json
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/setup.cfg
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/.gitignore
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/README.md
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/events/event.json
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.eslintignore
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.eslintrc.js
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.npmignore
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.prettierrc.js
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/app.ts
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/tsconfig.json
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external

#301 Update hello world ts to use correct error logging
  nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/app.ts
Labels: pr/external, stage/needs-triage

#305 Adding dotnet7 native aot template
  manifest-v2.json
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/.gitignore
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/Pipfile
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/README.md
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/cookiecutter.json
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/setup.cfg
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/tests/test_cookiecutter.py
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/.gitignore
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/README.md
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/events/event.json
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/omnisharp.json
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/Function.cs
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/aws-lambda-tools-defaults.json
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/src/HelloWorld/rd.xml
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/FunctionTest.cs
  provided.al2/nativeaot/dotnet7/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj
Labels: pr/external, stage/needs-triage

#304 Added MemorySize parameter to Hello-World template
  dotnet5.0-image/cookiecutter-aws-sam-hello-dotnet-lambda-image/{{cookiecutter.project_name}}/template.yaml
  dotnet6-image/cookiecutter-aws-sam-hello-dotnet-lambda-image/{{cookiecutter.project_name}}/template.yaml
  dotnet6/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml
  dotnet6/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/template.yaml
  dotnetcore3.1-image/cookiecutter-aws-sam-hello-dotnet-lambda-image/{{cookiecutter.project_name}}/template.yaml
  dotnetcore3.1/cookiecutter-aws-sam-hello-dotnet/{{cookiecutter.project_name}}/template.yaml
  dotnetcore3.1/cookiecutter-aws-sam-hello-powershell/{{cookiecutter.project_name}}/template.yaml
  go1.x-image/cookiecutter-aws-sam-hello-golang-lambda-image/{{cookiecutter.project_name}}/template.yaml
  go1.x/cookiecutter-aws-sam-eventbridge-hello-golang/{{cookiecutter.project_name}}/template.yaml
  go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/template.yaml
  java11-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/template.yaml
  java11-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/template.yaml
  java11/cookiecutter-aws-sam-eventbridge-hello-java-gradle/{{cookiecutter.project_name}}/template.yaml
  java11/cookiecutter-aws-sam-eventbridge-hello-java-maven/{{cookiecutter.project_name}}/template.yaml
  java11/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/template.yaml
  java11/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/template.yaml
  java8-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/template.yaml
  java8-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/template.yaml
  java8.al2-image/cookiecutter-aws-sam-hello-java-gradle-lambda-image/{{cookiecutter.project_name}}/template.yaml
  java8.al2-image/cookiecutter-aws-sam-hello-java-maven-lambda-image/{{cookiecutter.project_name}}/template.yaml
  java8.al2/cookiecutter-aws-sam-eventbridge-hello-java-gradle/{{cookiecutter.project_name}}/template.yaml
  java8.al2/cookiecutter-aws-sam-eventbridge-hello-java-maven/{{cookiecutter.project_name}}/template.yaml
  java8.al2/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/template.yaml
  java8.al2/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/template.yaml
  java8/cookiecutter-aws-sam-eventbridge-hello-java-gradle/{{cookiecutter.project_name}}/template.yaml
  java8/cookiecutter-aws-sam-eventbridge-hello-java-maven/{{cookiecutter.project_name}}/template.yaml
  java8/cookiecutter-aws-sam-hello-java-gradle/{{cookiecutter.project_name}}/template.yaml
  java8/cookiecutter-aws-sam-hello-java-maven/{{cookiecutter.project_name}}/template.yaml
  nodejs12.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/template.yaml
  nodejs12.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/template.yaml
  nodejs14.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/template.yaml
  nodejs14.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/template.yaml
  nodejs14.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
  nodejs16.x-image/cookiecutter-aws-sam-hello-nodejs-lambda-image/{{cookiecutter.project_name}}/template.yaml
  nodejs16.x/cookiecutter-aws-sam-hello-nodejs/{{cookiecutter.project_name}}/template.yaml
  nodejs16.x/cookiecutter-aws-sam-hello-powertools-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
  nodejs16.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
  python3.7-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml
  python3.7/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/template.yaml
  python3.8-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml
  python3.8/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/template.yaml
  python3.9-image/cookiecutter-aws-sam-hello-python-lambda-image/{{cookiecutter.project_name}}/template.yaml
  python3.9/cookiecutter-aws-sam-hello-python/{{cookiecutter.project_name}}/template.yaml
  ruby2.7-image/cookiecutter-aws-sam-hello-ruby-lambda-image/{{cookiecutter.project_name}}/template.yaml
  ruby2.7/cookiecutter-aws-sam-hello-ruby/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external, stage/needs-triage

#308 chore: Add CODEOWNERS file
  CODEOWNERS
Labels: pr/internal
