Repository aws/aws-sam-cli-app-templates, pull requests merged in 2022-02, with the labels that each got.

#188 fix: Set get-pip URL to 3.6
  buildspecs/buildspec-unittest-python3.6.yml
Labels: pr/internal

#184 feat: add TypeScript hello world template
  manifest.json
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/.gitignore
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/README.md
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/cookiecutter.json
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/setup.cfg
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/.gitignore
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/README.md
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/events/event.json
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.eslintignore
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.eslintrc.js
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.npmignore
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/.prettierrc.js
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/app.ts
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/hello-world/tsconfig.json
  nodejs14.x/cookiecutter-aws-sam-hello-typescript-nodejs/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external, maintainer/need-followup

#204 fix(dotnet6): Set .NET6 example as Hello-World
  manifest.json
Labels: pr/external

#205 Revert "fix(dotnet6): Set .NET6 example as Hello-World"
  manifest.json
Labels: pr/internal
