Repository aws/aws-sam-cli-app-templates, pull requests merged in 2022-05, with the labels that each got.

#236 fix: remove xray information from existing templates
  go1.x/cookiecutter-aws-sam-hello-golang/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external, maintainer/need-response

#165 Corrects indenting on Go Step Functions template
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockBuyer/main.go
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockBuyer/main_test.go
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockChecker/main.go
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockChecker/main_test.go
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockSeller/main.go
  go1.x/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/stockSeller/main_test.go
Labels: pr/external, maintainer/need-response

#212 Fix issue 197
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/Pipfile
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/cookiecutter.json
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/setup.cfg
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/events/event-sqs.json
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/omnisharp.json
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Function.cs
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}.csproj
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/template.yaml
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/FunctionTest.cs
  dotnet6/cookiecutter-aws-sam-quick-start-sqs-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj
  manifest-v2.json
  tests/integration/unit_test/test_unit_test_dotnet6.py
Labels: pr/external, maintainer/need-response

#217 fix(dotnet6): fix hello step fuction samplle app
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/StockBuyer/Function.cs
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/StockBuyer/StockBuyer.csproj
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/StockChecker/Function.cs
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/StockChecker/StockChecker.csproj
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/StockSeller/Function.cs
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/functions/StockSeller/StockSeller.csproj
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/tests/StockBuyer.Test/FunctionTest.cs
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/tests/StockChecker.Test/FunctionTest.cs
  dotnet6/cookiecutter-aws-sam-hello-step-functions-sample-app/{{cookiecutter.project_name}}/tests/StockSeller.Test/FunctionTest.cs
Labels: pr/external

#159 added missing executionArn as parameter to waitExecution
  nodejs12.x/cookiecutter-aws-sam-step-functions-sample-app/{{cookiecutter.project_name}}/integration-tests/test-state-machine.js
Labels: pr/external, maintainer/need-response

#130 fix: Remove isDynamicTemplate from java11/cookiecutter-aws-sam-step-functions-sample-app-gradle app
  manifest-v2.json
Labels: pr/internal

#218 196 dotnet6 web backend
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/cookiecutter.json
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/setup.cfg
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/omnisharp.json
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Controllers/BooksController.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Entities/Book.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Program.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Readme.md
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Repositories/BookRepository.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Repositories/IBookRepository.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/appsettings.Development.json
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/appsettings.json
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/aws-lambda-tools-defaults.json
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}.csproj
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/template.yaml
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/tests/{{cookiecutter.project_name}}.Tests/BookControllerTest.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/tests/{{cookiecutter.project_name}}.Tests/MockBookRepository.cs
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/tests/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj
  dotnet6/cookiecutter-aws-sam-quick-start-web-dotnet/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}.sln
  manifest-v2.json
  tests/integration/build_invoke/test_build_invoke_dotnet6.py
  tests/integration/unit_test/test_unit_test_dotnet6.py
Labels: pr/external

#214 feat(dotnet6): SAM quick start from scratch
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/Pipfile
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/cookiecutter.json
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/setup.cfg
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/omnisharp.json
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Function.cs
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}.csproj
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/template.yaml
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/FunctionTest.cs
  dotnet6/cookiecutter-aws-sam-quick-start-from-scratch-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj
  manifest-v2.json
  tests/integration/build_invoke/test_build_invoke_dotnet6.py
  tests/integration/unit_test/test_unit_test_dotnet6.py
Labels: pr/external

#238 fix: add nodejs16 image type to the manifest
  manifest-v2.json
Labels: pr/internal

#215 feat(dotnet6): SAM template for .NET 6 C# Quick Start: Scheduled Events
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/cookiecutter.json
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/setup.cfg
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/.gitignore
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/README.md
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/events/event-cloudwatch-event.json
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/omnisharp.json
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Function.cs
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/Readme.md
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/aws-lambda-tools-defaults.json
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/src/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}.csproj
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/template.yaml
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/FunctionTest.cs
  dotnet6/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj
  manifest-v2.json
  tests/integration/build_invoke/test_build_invoke_dotnet6.py
  tests/integration/unit_test/test_unit_test_dotnet6.py
Labels: pr/external

#240 fix: fix manifest-v2.json file and add GH action to validate this from now on
  .github/workflows/manifest-v2-check.yml
  manifest-v2.json
Labels: pr/internal

#243 feat: improve new PR and issue labeling for triaging
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/other.md
  .github/workflows/pr-labeler.yml
Labels: pr/internal
