Repository aws/aws-sam-cli-app-templates, pull requests merged in 2023-05, with the labels that each got.

#410 remove dotnet5 templates
  .github/workflows/build_test_invoke.yml
  dotnet5/hello-img/.gitignore
  dotnet5/hello-img/Pipfile
  dotnet5/hello-img/README.md
  dotnet5/hello-img/cookiecutter.json
  dotnet5/hello-img/setup.cfg
  dotnet5/hello-img/tests/test_cookiecutter.py
  dotnet5/hello-img/{{cookiecutter.project_name}}/.gitignore
  dotnet5/hello-img/{{cookiecutter.project_name}}/README.md
  dotnet5/hello-img/{{cookiecutter.project_name}}/events/event.json
  dotnet5/hello-img/{{cookiecutter.project_name}}/omnisharp.json
  dotnet5/hello-img/{{cookiecutter.project_name}}/src/HelloWorld/Dockerfile
  dotnet5/hello-img/{{cookiecutter.project_name}}/src/HelloWorld/Function.cs
  dotnet5/hello-img/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
  dotnet5/hello-img/{{cookiecutter.project_name}}/src/HelloWorld/aws-lambda-tools-defaults.json
  dotnet5/hello-img/{{cookiecutter.project_name}}/template.yaml
  dotnet5/hello-img/{{cookiecutter.project_name}}/test/HelloWorld.Test/FunctionTest.cs
  dotnet5/hello-img/{{cookiecutter.project_name}}/test/HelloWorld.Test/HelloWorld.Tests.csproj
  manifest-v2.json
  manifest.json
  tests/integration/build_invoke/dotnet/test_build_invoke_dotnet5_0.py
Labels: pr/internal

#416 Update dotnet6 Powertools template 1.2.0
  dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
Labels: pr/external, stage/needs-triage

#418 Running pytest in multi-threads
  .github/workflows/build_test_invoke.yml
  tests/integration/unit_test/unit_test_base.py
Labels: pr/external
