Repository aws/aws-sam-cli-app-templates, pull requests merged in 2023-02, with the labels that each got.

#334 feat: AWS Lambda Powertools for Python templates
  manifest-v2.json
  python3.7/hello-pt/.gitignore
  python3.7/hello-pt/README.md
  python3.7/hello-pt/__init__.py
  python3.7/hello-pt/cookiecutter.json
  python3.7/hello-pt/setup.cfg
  python3.7/hello-pt/{{ cookiecutter.project_name }}/.gitignore
  python3.7/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.7/hello-pt/{{ cookiecutter.project_name }}/__init__.py
  python3.7/hello-pt/{{ cookiecutter.project_name }}/events/hello.json
  python3.7/hello-pt/{{ cookiecutter.project_name }}/hello_world/__init__.py
  python3.7/hello-pt/{{ cookiecutter.project_name }}/hello_world/app.py
  python3.7/hello-pt/{{ cookiecutter.project_name }}/hello_world/requirements.txt
  python3.7/hello-pt/{{ cookiecutter.project_name }}/template.yaml
  python3.7/hello-pt/{{ cookiecutter.project_name }}/tests/__init__.py
  python3.7/hello-pt/{{ cookiecutter.project_name }}/tests/requirements.txt
  python3.7/hello-pt/{{ cookiecutter.project_name }}/tests/unit/__init__.py
  python3.7/hello-pt/{{ cookiecutter.project_name }}/tests/unit/test_handler.py
  python3.8/hello-pt/.gitignore
  python3.8/hello-pt/README.md
  python3.8/hello-pt/__init__.py
  python3.8/hello-pt/cookiecutter.json
  python3.8/hello-pt/setup.cfg
  python3.8/hello-pt/{{ cookiecutter.project_name }}/.gitignore
  python3.8/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.8/hello-pt/{{ cookiecutter.project_name }}/__init__.py
  python3.8/hello-pt/{{ cookiecutter.project_name }}/events/hello.json
  python3.8/hello-pt/{{ cookiecutter.project_name }}/hello_world/__init__.py
  python3.8/hello-pt/{{ cookiecutter.project_name }}/hello_world/app.py
  python3.8/hello-pt/{{ cookiecutter.project_name }}/hello_world/requirements.txt
  python3.8/hello-pt/{{ cookiecutter.project_name }}/template.yaml
  python3.8/hello-pt/{{ cookiecutter.project_name }}/tests/__init__.py
  python3.8/hello-pt/{{ cookiecutter.project_name }}/tests/requirements.txt
  python3.8/hello-pt/{{ cookiecutter.project_name }}/tests/unit/__init__.py
  python3.8/hello-pt/{{ cookiecutter.project_name }}/tests/unit/test_handler.py
  python3.9/hello-pt/.gitignore
  python3.9/hello-pt/README.md
  python3.9/hello-pt/__init__.py
  python3.9/hello-pt/cookiecutter.json
  python3.9/hello-pt/setup.cfg
  python3.9/hello-pt/{{ cookiecutter.project_name }}/.gitignore
  python3.9/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.9/hello-pt/{{ cookiecutter.project_name }}/__init__.py
  python3.9/hello-pt/{{ cookiecutter.project_name }}/events/hello.json
  python3.9/hello-pt/{{ cookiecutter.project_name }}/hello_world/__init__.py
  python3.9/hello-pt/{{ cookiecutter.project_name }}/hello_world/app.py
  python3.9/hello-pt/{{ cookiecutter.project_name }}/hello_world/requirements.txt
  python3.9/hello-pt/{{ cookiecutter.project_name }}/template.yaml
  python3.9/hello-pt/{{ cookiecutter.project_name }}/tests/__init__.py
  python3.9/hello-pt/{{ cookiecutter.project_name }}/tests/requirements.txt
  python3.9/hello-pt/{{ cookiecutter.project_name }}/tests/unit/__init__.py
  python3.9/hello-pt/{{ cookiecutter.project_name }}/tests/unit/test_handler.py
  tests/integration/unit_test/test_unit_test_python3_7.py
  tests/integration/unit_test/test_unit_test_python3_8.py
  tests/integration/unit_test/test_unit_test_python3_9.py
Labels: pr/external

#341 Rust cargo lambda
  al2/rust/hello/{{ cookiecutter.project_slug }}/Makefile
  al2/rust/hello/{{ cookiecutter.project_slug }}/README.md
  al2/rust/hello/{{ cookiecutter.project_slug }}/rust_app/Cargo.toml
  al2/rust/hello/{{ cookiecutter.project_slug }}/rust_app/src/main.rs
  al2/rust/hello/{{ cookiecutter.project_slug }}/template.yaml
  buildspec.yml
  buildspecs/buildspec-rust.yml
  buildspecs/buildspec-unittest-rust.yml
  tests/integration/base.py
  tests/integration/build_invoke/build_invoke_base.py
  tests/integration/build_invoke/test_build_invoke_rust.py
Labels: pr/internal

#349 feat: AWS Lambda Powertools for Java templates
  java11/hello-pt-maven/README.md
  java11/hello-pt-maven/__init__.py
  java11/hello-pt-maven/cookiecutter.json
  java11/hello-pt-maven/tests/__init__.py
  java11/hello-pt-maven/tests/test_cookiecutter.py
  java11/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/pom.xml
  java11/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
  java11/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/log4j.xml
  java11/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
  java11/hello-pt-maven/{{cookiecutter.project_name}}/README.md
  java11/hello-pt-maven/{{cookiecutter.project_name}}/events/event.json
  java11/hello-pt-maven/{{cookiecutter.project_name}}/template.yaml
  java8.al2/hello-pt-maven/README.md
  java8.al2/hello-pt-maven/__init__.py
  java8.al2/hello-pt-maven/cookiecutter.json
  java8.al2/hello-pt-maven/tests/__init__.py
  java8.al2/hello-pt-maven/tests/test_cookiecutter.py
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/pom.xml
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/log4j.xml
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/README.md
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/events/event.json
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/template.yaml
  java8/hello-pt-maven/README.md
  java8/hello-pt-maven/__init__.py
  java8/hello-pt-maven/cookiecutter.json
  java8/hello-pt-maven/tests/__init__.py
  java8/hello-pt-maven/tests/test_cookiecutter.py
  java8/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/pom.xml
  java8/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/java/helloworld/App.java
  java8/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/log4j.xml
  java8/hello-pt-maven/{{cookiecutter.project_name}}/HelloWorldFunction/src/test/java/helloworld/AppTest.java
  java8/hello-pt-maven/{{cookiecutter.project_name}}/README.md
  java8/hello-pt-maven/{{cookiecutter.project_name}}/events/event.json
  java8/hello-pt-maven/{{cookiecutter.project_name}}/template.yaml
  manifest-v2.json
  tests/integration/unit_test/test_unit_test_java11.py
  tests/integration/unit_test/test_unit_test_java8.py
  tests/integration/unit_test/test_unit_test_java8_al2.py
Labels: pr/external, stage/needs-triage

#345 chore: Updated ioutil.ReadAll to io.ReadAll
  al2/go/event-bridge-schema/{{cookiecutter.project_name}}/{{cookiecutter.function_name}}/main_test.go
  al2/go/event-bridge/{{cookiecutter.project_name}}/hello-world/main_test.go
  al2/go/hello-img/{{cookiecutter.project_name}}/hello-world/main.go
  al2/go/hello/{{cookiecutter.project_name}}/hello-world/main.go
  buildspec.yml
  go1.x/event-bridge-schema/{{cookiecutter.project_name}}/{{cookiecutter.function_name}}/main_test.go
  go1.x/event-bridge/{{cookiecutter.project_name}}/hello-world/main_test.go
  go1.x/hello-img/{{cookiecutter.project_name}}/hello-world/main.go
  go1.x/hello/{{cookiecutter.project_name}}/hello-world/main.go
Labels: pr/internal

#346 feat: Added sed to sub in mock ARN for testing
  nodejs12.x/step-func-conn/{{cookiecutter.project_name}}/makefile
  nodejs14.x/step-func-conn/{{cookiecutter.project_name}}/makefile
  nodejs14.x/step-func/{{cookiecutter.project_name}}/makefile
  nodejs16.x/step-func-conn/{{cookiecutter.project_name}}/makefile
  nodejs16.x/step-func/{{cookiecutter.project_name}}/makefile
  nodejs18.x/step-func/{{cookiecutter.project_name}}/makefile
Labels: pr/internal

#353 Add gitignore files into rust templates
  al2/rust/hello-ddb/{{ cookiecutter.project_slug }}/.gitignore
  al2/rust/hello/{{ cookiecutter.project_slug }}/.gitignore
Labels: pr/internal
