Repository aws/aws-sam-cli-app-templates, pull requests merged in 2023-04, with the labels that each got.

#386 Fix readme in powertools templates
  .github/workflows/build_test_invoke.yml
  nodejs14.x/hello-ts-pt/README.md
  nodejs16.x/hello-ts-pt/README.md
  nodejs18.x/hello-ts-pt/README.md
  python3.7/hello-pt/README.md
  python3.7/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.8/hello-pt/README.md
  python3.8/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.9/hello-pt/README.md
  python3.9/hello-pt/{{ cookiecutter.project_name }}/README.md
Labels: pr/internal

#381 fix: Fix TypeScript tests using esbuild-jest
  .gitignore
  nodejs14.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/app.ts
  nodejs14.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs14.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs14.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs14.x/hello-ts/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs14.x/hello-ts/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs14.x/hello-ts/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs16.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/app.ts
  nodejs16.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs16.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs16.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs16.x/hello-ts/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs16.x/hello-ts/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs16.x/hello-ts/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs18.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/app.ts
  nodejs18.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs18.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs18.x/hello-ts-pt/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
  nodejs18.x/hello-ts/{{cookiecutter.project_name}}/hello-world/jest.config.ts
  nodejs18.x/hello-ts/{{cookiecutter.project_name}}/hello-world/package.json
  nodejs18.x/hello-ts/{{cookiecutter.project_name}}/hello-world/tests/unit/test-handler.test.ts
Labels: pr/internal

#387 add lint test to integ base
  dotnetcore3.1/cw-event/{{cookiecutter.project_name}}/template.yaml
  tests/integration/base.py
  tests/integration/build_invoke/build_invoke_base.py
  tests/integration/build_invoke/dotnet/test_build_invoke_dotnetcore3_1.py
  tests/integration/build_invoke/node/test_node_12.py
  tests/integration/build_invoke/python/test_python_3_10.py
  tests/integration/unit_test/test_unit_test_dotnetcore3_1.py
  tests/integration/unit_test/test_unit_test_nodejs12_x.py
  tests/integration/unit_test/test_unit_test_python3_10.py
Labels: pr/internal

#390 ci: add feat* rule to run github actions
  .github/workflows/build_test_invoke.yml
Labels: pr/internal

#396 Replace cloudformation cli with sam cli in Readme files - Java templates
  java11/hello-gradle/{{cookiecutter.project_name}}/README.md
  java11/hello-img-gradle/{{cookiecutter.project_name}}/README.md
  java11/hello-img-maven/{{cookiecutter.project_name}}/README.md
  java11/hello-maven/{{cookiecutter.project_name}}/README.md
  java11/hello-pt-maven/{{cookiecutter.project_name}}/README.md
  java11/step-func-gradle/{{cookiecutter.project_name}}/README.md
  java11/step-func-maven/{{cookiecutter.project_name}}/README.md
  java8.al2/hello-gradle/{{cookiecutter.project_name}}/README.md
  java8.al2/hello-img-gradle/{{cookiecutter.project_name}}/README.md
  java8.al2/hello-img-maven/{{cookiecutter.project_name}}/README.md
  java8.al2/hello-maven/{{cookiecutter.project_name}}/README.md
  java8.al2/hello-pt-maven/{{cookiecutter.project_name}}/README.md
  java8.al2/step-func-gradle/{{cookiecutter.project_name}}/README.md
  java8.al2/step-func-maven/{{cookiecutter.project_name}}/README.md
  java8/hello-gradle/{{cookiecutter.project_name}}/README.md
  java8/hello-img-gradle/{{cookiecutter.project_name}}/README.md
  java8/hello-img-maven/{{cookiecutter.project_name}}/README.md
  java8/hello-maven/{{cookiecutter.project_name}}/README.md
  java8/hello-pt-maven/{{cookiecutter.project_name}}/README.md
  java8/step-func-gradle/{{cookiecutter.project_name}}/README.md
  java8/step-func-maven/{{cookiecutter.project_name}}/README.md
Labels: documentation, pr/external

#391 update powertools to v1.0.1
  dotnet6/hello-pt/{{cookiecutter.project_name}}/src/HelloWorld/HelloWorld.csproj
  dotnet6/hello-pt/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external, stage/needs-triage

#394 Replace cloudformation cli with sam cli in Readme files - Python templates
  python3.10/apigw-pytorch/{{cookiecutter.project_name}}/README.md
  python3.10/apigw-scikit/{{cookiecutter.project_name}}/README.md
  python3.10/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
  python3.10/apigw-xgboost/{{cookiecutter.project_name}}/README.md
  python3.10/efs/{{cookiecutter.project_name}}/README.md
  python3.10/hello-img/{{cookiecutter.project_name}}/README.md
  python3.10/hello/{{cookiecutter.project_name}}/README.md
  python3.10/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.10/step-func-etl/{{cookiecutter.project_name}}/README.md
  python3.10/step-func/{{cookiecutter.project_name}}/README.md
  python3.10/web-conn/{{cookiecutter.project_name}}/README.md
  python3.7/hello-img/{{cookiecutter.project_name}}/README.md
  python3.7/hello/{{cookiecutter.project_name}}/README.md
  python3.7/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.7/step-func/{{cookiecutter.project_name}}/README.md
  python3.7/web-conn/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-pytorch/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-scikit/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-xgboost/{{cookiecutter.project_name}}/README.md
  python3.8/efs/{{cookiecutter.project_name}}/README.md
  python3.8/hello-img/{{cookiecutter.project_name}}/README.md
  python3.8/hello/{{cookiecutter.project_name}}/README.md
  python3.8/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.8/step-func/{{cookiecutter.project_name}}/README.md
  python3.8/web-conn/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-pytorch/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-scikit/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-xgboost/{{cookiecutter.project_name}}/README.md
  python3.9/efs/{{cookiecutter.project_name}}/README.md
  python3.9/hello-img/{{cookiecutter.project_name}}/README.md
  python3.9/hello/{{cookiecutter.project_name}}/README.md
  python3.9/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.9/step-func-etl/{{cookiecutter.project_name}}/README.md
  python3.9/step-func/{{cookiecutter.project_name}}/README.md
  python3.9/web-conn/{{cookiecutter.project_name}}/README.md
Labels: documentation, pr/external

#393 Replace cloudformation cli with sam cli in Readme files
  al2/go/step-func/{{cookiecutter.project_name}}/README.md
  dotnet5/hello-img/{{cookiecutter.project_name}}/README.md
  dotnet6/cw-event/{{cookiecutter.project_name}}/README.md
  dotnet6/hello-ps/{{cookiecutter.project_name}}/README.md
  dotnet6/scratch/{{cookiecutter.project_name}}/README.md
  dotnet6/sqs/{{cookiecutter.project_name}}/README.md
  dotnet6/web/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/cw-event/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/hello-img/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/hello-ps/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/hello/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/s3/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/scratch/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/sns/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/sqs/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/step-func/{{cookiecutter.project_name}}/README.md
  dotnetcore3.1/web/{{cookiecutter.project_name}}/README.md
  go1.x/step-func/{{cookiecutter.project_name}}/README.md
  ruby2.7/hello-img/{{cookiecutter.project_name}}/README.md
  ruby2.7/hello/{{cookiecutter.project_name}}/README.md
  ruby2.7/step-func/{{cookiecutter.project_name}}/README.md
Labels: documentation, pr/external

#389 Unused Body struct removed from the hello world Rust example
  al2/rust/hello/{{ cookiecutter.project_slug }}/rust_app/src/main.rs
Labels: enhancement, pr/external

#397 feat: Templates for Lambda response streaming
  manifest-v2.json
  nodejs16.x/response-streaming/.gitignore
  nodejs16.x/response-streaming/README.md
  nodejs16.x/response-streaming/cookiecutter.json
  nodejs16.x/response-streaming/setup.cfg
  nodejs16.x/response-streaming/{{cookiecutter.project_name}}/.gitignore
  nodejs16.x/response-streaming/{{cookiecutter.project_name}}/README.md
  nodejs16.x/response-streaming/{{cookiecutter.project_name}}/__tests__/unit/index.test.js
  nodejs16.x/response-streaming/{{cookiecutter.project_name}}/package.json
  nodejs16.x/response-streaming/{{cookiecutter.project_name}}/src/index.js
  nodejs16.x/response-streaming/{{cookiecutter.project_name}}/template.yaml
  nodejs18.x/response-streaming/.gitignore
  nodejs18.x/response-streaming/README.md
  nodejs18.x/response-streaming/cookiecutter.json
  nodejs18.x/response-streaming/setup.cfg
  nodejs18.x/response-streaming/{{cookiecutter.project_name}}/.gitignore
  nodejs18.x/response-streaming/{{cookiecutter.project_name}}/README.md
  nodejs18.x/response-streaming/{{cookiecutter.project_name}}/__tests__/unit/index.test.js
  nodejs18.x/response-streaming/{{cookiecutter.project_name}}/package.json
  nodejs18.x/response-streaming/{{cookiecutter.project_name}}/src/index.js
  nodejs18.x/response-streaming/{{cookiecutter.project_name}}/template.yaml
  tests/integration/build_invoke/node/test_node_16.py
  tests/integration/build_invoke/node/test_node_18.py
  tests/integration/unit_test/test_unit_test_nodejs16_x.py
  tests/integration/unit_test/test_unit_test_nodejs18_x.py
Labels: pr/external, stage/needs-triage

#403 fix: Bump torchvision and added build tests
  python3.10/apigw-pytorch/cookiecutter.json
  python3.10/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
  python3.8/apigw-pytorch/cookiecutter.json
  python3.8/apigw-pytorch/{{cookiecutter.project_name}}/app/requirements.txt
  python3.9/apigw-pytorch/cookiecutter.json
  tests/integration/build_invoke/python/test_python_3_10.py
  tests/integration/build_invoke/python/test_python_3_8.py
  tests/integration/build_invoke/python/test_python_3_9.py
Labels: pr/internal

#405 Go template for response streaming
  al2/go/response-streaming/.gitignore
  al2/go/response-streaming/cookiecutter.json
  al2/go/response-streaming/setup.cfg
  al2/go/response-streaming/{{cookiecutter.project_name}}/README.md
  al2/go/response-streaming/{{cookiecutter.project_name}}/hello/go.mod
  al2/go/response-streaming/{{cookiecutter.project_name}}/hello/go.sum
  al2/go/response-streaming/{{cookiecutter.project_name}}/hello/main.go
  al2/go/response-streaming/{{cookiecutter.project_name}}/hello/main_test.go
  al2/go/response-streaming/{{cookiecutter.project_name}}/template.yaml
  manifest-v2.json
  tests/integration/build_invoke/test_build_invoke_go1_x.py
  tests/integration/unit_test/test_unit_test_go1_x.py
Labels: pr/external

#400 chore: add py3.10 linting back to tests
  tests/integration/build_invoke/python/test_python_3_10.py
  tests/integration/unit_test/test_unit_test_python3_10.py
Labels: pr/internal

#406 Make bash scripts for Python 3.7 projects more consistent
  python3.7/event-bridge-schema/cookiecutter.json
  python3.7/event-bridge-schema/{{cookiecutter.project_name}}/README.md
  python3.7/event-bridge/cookiecutter.json
  python3.7/event-bridge/{{cookiecutter.project_name}}/README.md
  python3.7/hello-img/cookiecutter.json
  python3.7/hello-img/{{cookiecutter.project_name}}/README.md
  python3.7/hello-pt/cookiecutter.json
  python3.7/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.7/hello/cookiecutter.json
  python3.7/hello/{{cookiecutter.project_name}}/README.md
  python3.7/step-func-conn/cookiecutter.json
  python3.7/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.7/step-func/cookiecutter.json
  python3.7/step-func/{{cookiecutter.project_name}}/README.md
  python3.7/web-conn/cookiecutter.json
  python3.7/web-conn/{{cookiecutter.project_name}}/README.md
Labels: pr/external, stage/needs-triage

#409 Make bash scripts for Python 3.10 projects more consistent
  python3.10/apigw-pytorch/cookiecutter.json
  python3.10/apigw-pytorch/{{cookiecutter.project_name}}/README.md
  python3.10/apigw-scikit/cookiecutter.json
  python3.10/apigw-scikit/{{cookiecutter.project_name}}/README.md
  python3.10/apigw-tensorflow/cookiecutter.json
  python3.10/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
  python3.10/apigw-xgboost/cookiecutter.json
  python3.10/apigw-xgboost/{{cookiecutter.project_name}}/README.md
  python3.10/efs/cookiecutter.json
  python3.10/efs/{{cookiecutter.project_name}}/README.md
  python3.10/event-bridge-schema/cookiecutter.json
  python3.10/event-bridge-schema/{{cookiecutter.project_name}}/README.md
  python3.10/event-bridge/cookiecutter.json
  python3.10/event-bridge/{{cookiecutter.project_name}}/README.md
  python3.10/hello-img/cookiecutter.json
  python3.10/hello-img/{{cookiecutter.project_name}}/README.md
  python3.10/hello-pt/cookiecutter.json
  python3.10/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.10/hello/cookiecutter.json
  python3.10/hello/{{cookiecutter.project_name}}/README.md
  python3.10/step-func-conn/cookiecutter.json
  python3.10/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.10/step-func-etl/cookiecutter.json
  python3.10/step-func-etl/{{cookiecutter.project_name}}/README.md
  python3.10/step-func/cookiecutter.json
  python3.10/step-func/{{cookiecutter.project_name}}/README.md
  python3.10/web-conn/cookiecutter.json
  python3.10/web-conn/{{cookiecutter.project_name}}/README.md
Labels: pr/external, stage/needs-triage

#407 Make bash scripts for Python 3.8 projects more consistent
  python3.8/apigw-pytorch/cookiecutter.json
  python3.8/apigw-pytorch/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-scikit/cookiecutter.json
  python3.8/apigw-scikit/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-tensorflow/cookiecutter.json
  python3.8/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
  python3.8/apigw-xgboost/cookiecutter.json
  python3.8/apigw-xgboost/{{cookiecutter.project_name}}/README.md
  python3.8/efs/cookiecutter.json
  python3.8/efs/{{cookiecutter.project_name}}/README.md
  python3.8/event-bridge-schema/cookiecutter.json
  python3.8/event-bridge-schema/{{cookiecutter.project_name}}/README.md
  python3.8/event-bridge/cookiecutter.json
  python3.8/event-bridge/{{cookiecutter.project_name}}/README.md
  python3.8/hello-img/cookiecutter.json
  python3.8/hello-img/{{cookiecutter.project_name}}/README.md
  python3.8/hello-pt/cookiecutter.json
  python3.8/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.8/hello/cookiecutter.json
  python3.8/hello/{{cookiecutter.project_name}}/README.md
  python3.8/step-func-conn/cookiecutter.json
  python3.8/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.8/step-func/cookiecutter.json
  python3.8/step-func/{{cookiecutter.project_name}}/README.md
  python3.8/web-conn/cookiecutter.json
  python3.8/web-conn/{{cookiecutter.project_name}}/README.md
Labels: pr/external, stage/needs-triage

#408 Make bash scripts for Python 3.9 projects more consistent
  python3.9/apigw-pytorch/cookiecutter.json
  python3.9/apigw-pytorch/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-scikit/cookiecutter.json
  python3.9/apigw-scikit/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-tensorflow/cookiecutter.json
  python3.9/apigw-tensorflow/{{cookiecutter.project_name}}/README.md
  python3.9/apigw-xgboost/cookiecutter.json
  python3.9/apigw-xgboost/{{cookiecutter.project_name}}/README.md
  python3.9/efs/cookiecutter.json
  python3.9/efs/{{cookiecutter.project_name}}/README.md
  python3.9/event-bridge-schema/cookiecutter.json
  python3.9/event-bridge-schema/{{cookiecutter.project_name}}/README.md
  python3.9/event-bridge/cookiecutter.json
  python3.9/event-bridge/{{cookiecutter.project_name}}/README.md
  python3.9/hello-img/cookiecutter.json
  python3.9/hello-img/{{cookiecutter.project_name}}/README.md
  python3.9/hello-pt/cookiecutter.json
  python3.9/hello-pt/{{ cookiecutter.project_name }}/README.md
  python3.9/hello/cookiecutter.json
  python3.9/hello/{{cookiecutter.project_name}}/README.md
  python3.9/step-func-conn/cookiecutter.json
  python3.9/step-func-conn/{{cookiecutter.project_name}}/README.md
  python3.9/step-func-etl/cookiecutter.json
  python3.9/step-func-etl/{{cookiecutter.project_name}}/README.md
  python3.9/step-func/cookiecutter.json
  python3.9/step-func/{{cookiecutter.project_name}}/README.md
  python3.9/web-conn/cookiecutter.json
  python3.9/web-conn/{{cookiecutter.project_name}}/README.md
Labels: pr/external, stage/needs-triage
