Repository aws/aws-sam-cli-app-templates, pull requests merged in 2023-03, with the labels that each got.

#355 chore(manifest): sync powertools examples useCaseName/displayName
  manifest-v2.json
Labels: pr/external, stage/needs-triage

#299 fix: issue#298 - Bug: GraalVM builds on Non-amd64 platform fail #298
  al2/graalvm/11/gradle/README.md
  al2/graalvm/11/gradle/cookiecutter.json
  al2/graalvm/11/gradle/{{cookiecutter.project_name}}/Dockerfile
  al2/graalvm/11/gradle/{{cookiecutter.project_name}}/template.yaml
  al2/graalvm/11/maven/cookiecutter.json
  al2/graalvm/11/maven/{{cookiecutter.project_name}}/Dockerfile
  al2/graalvm/11/maven/{{cookiecutter.project_name}}/template.yaml
  al2/graalvm/17/gradle/cookiecutter.json
  al2/graalvm/17/gradle/{{cookiecutter.project_name}}/Dockerfile
  al2/graalvm/17/gradle/{{cookiecutter.project_name}}/template.yaml
  al2/graalvm/17/maven/cookiecutter.json
  al2/graalvm/17/maven/{{cookiecutter.project_name}}/Dockerfile
  al2/graalvm/17/maven/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external

#360 Quick and dirty fix for https://github.com/aws/aws-sam-cli/issues/4860
  dotnet6/hello-pt/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external, stage/needs-triage

#362 Optimize docker images for python
  python3.7/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile
  python3.8/apigw-pytorch/{{cookiecutter.project_name}}/app/Dockerfile
  python3.8/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
  python3.8/apigw-tensorflow/{{cookiecutter.project_name}}/app/Dockerfile
  python3.8/apigw-xgboost/{{cookiecutter.project_name}}/app/Dockerfile
  python3.8/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile
  python3.9/apigw-pytorch/{{cookiecutter.project_name}}/app/Dockerfile
  python3.9/apigw-scikit/{{cookiecutter.project_name}}/app/Dockerfile
  python3.9/apigw-tensorflow/{{cookiecutter.project_name}}/app/Dockerfile
  python3.9/apigw-xgboost/{{cookiecutter.project_name}}/app/Dockerfile
  python3.9/hello-img/{{cookiecutter.project_name}}/hello_world/Dockerfile
Labels: pr/external, stage/needs-triage

#358 feat: Moved tests to Github Actions
  .github/actions/aws-sam-cli-develop/action.yml
  .github/workflows/build_test_invoke.yml
  .travis.yml
  buildspec.yml
  buildspecs/README.md
  buildspecs/buildspec-build-invoke-image.yml
  buildspecs/buildspec-build-invoke.yml
  buildspecs/buildspec-dotnet5.0.yml
  buildspecs/buildspec-dotnet6.yml
  buildspecs/buildspec-dotnetcore3.1.yml
  buildspecs/buildspec-go1.x.yml
  buildspecs/buildspec-graalvm.yml
  buildspecs/buildspec-rust.yml
  buildspecs/buildspec-unittest-java11.yml
  buildspecs/buildspec-unittest-java8-al2.yml
  buildspecs/buildspec-unittest-java8.yml
  buildspecs/buildspec-unittest-nodejs-12.x.yml
  buildspecs/buildspec-unittest-nodejs-14.x.yml
  buildspecs/buildspec-unittest-nodejs-16.x.yml
  buildspecs/buildspec-unittest-nodejs-18.x.yml
  buildspecs/buildspec-unittest-python3.7.yml
  buildspecs/buildspec-unittest-python3.8.yml
  buildspecs/buildspec-unittest-python3.9.yml
  buildspecs/buildspec-unittest-ruby2.7.yml
  tests/integration/build_invoke/dotnet/__init__.py
  tests/integration/build_invoke/dotnet/test_build_invoke_dotnet5_0.py
  tests/integration/build_invoke/dotnet/test_build_invoke_dotnet6.py
  tests/integration/build_invoke/dotnet/test_build_invoke_dotnet7.py
  tests/integration/build_invoke/dotnet/test_build_invoke_dotnetcore3_1.py
  tests/integration/build_invoke/java/__init__.py
  tests/integration/build_invoke/java/test_java_11.py
  tests/integration/build_invoke/java/test_java_11_al2.py
  tests/integration/build_invoke/java/test_java_8.py
  tests/integration/build_invoke/java/test_java_8_al2.py
  tests/integration/build_invoke/node/__init__.py
  tests/integration/build_invoke/node/test_node_12.py
  tests/integration/build_invoke/node/test_node_14.py
  tests/integration/build_invoke/node/test_node_16.py
  tests/integration/build_invoke/node/test_node_18.py
  tests/integration/build_invoke/python/__init__.py
  tests/integration/build_invoke/python/test_python_3_7.py
  tests/integration/build_invoke/python/test_python_3_8.py
  tests/integration/build_invoke/python/test_python_3_9.py
  tests/integration/build_invoke/test_build_invoke.py
  tests/integration/build_invoke/test_build_invoke_image.py
  tests/integration/build_invoke/test_ruby_2_7.py
  tests/integration/unit_test/test_unit_test_python3_7.py
  tests/integration/unit_test/test_unit_test_python3_8.py
Labels: pr/internal

#368 chore: Mark Dependabot PRs as internal
  .github/workflows/pr-labeler.yml
Labels: pr/internal

#365 fix: add py3.10 tests back
  .github/workflows/build_test_invoke.yml
Labels: pr/internal

#359 Add `OpenApiVersion` to dotnet templates
  dotnet6/hello-pt/{{cookiecutter.project_name}}/template.yaml
Labels: pr/external

#370 Mock S3 response for unit test
  dotnetcore3.1/s3/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/FunctionTest.cs
  dotnetcore3.1/s3/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj
  tests/integration/unit_test/test_unit_test_dotnetcore3_1.py
Labels: pr/external

#380 feat: Added merge group triggers to required Github Action workflows
  .github/workflows/build_test_invoke.yml
  .github/workflows/manifest-backward-compability-check.yml
  .github/workflows/manifest-v2-check.yml
Labels: pr/internal

#372 fix: use correct app template name for the rust dynamo db template
  manifest-v2.json
Labels: pr/internal
